package:
  name: xommons
  version: '1.0.0'

source:
  git_url: https://github.com/mdw771/xommons.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - xraylib

test:
  # Python imports
  imports:
    - xommons

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
