#!/usr/bin/env python
# -*- coding: utf-8 -*-

import numpy as np
import matplotlib.pyplot as plt
import h5py
import tqdm
import scipy.io
import tifffile

import sys
import os
import argparse

import xommons.io as xio


parser = argparse.ArgumentParser()
parser.add_argument('filename')
parser.add_argument('--key', default="object", help="key to dump")
args = parser.parse_args()

fname = args.filename
key = args.key

try:
    f = xio.load_h5(fname)
except:
    f = xio.load_mat(fname)

val = f[key]

if key in ["object", "probe"]:
    val = xio.matlab_complex_to_array(val)
    xio.complex_image_to_tiff(val, os.path.splitext(fname)[0])
else:
    print(val)

f.close()
