#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import argparse
import re
import glob
import fnmatch
import tifffile
import numpy as np


parser = argparse.ArgumentParser()
parser.add_argument('dir')
parser.add_argument("--pattern", default="*.tif*")
parser.add_argument("--output", default="combined.tiff")
args = parser.parse_args()

images = []
dir = args.dir
for root, dirs, files in os.walk(dir):
    for file in files:
        if fnmatch.fnmatch(file, args.pattern):
            print(os.path.join(root, file))
            images.append(tifffile.imread(os.path.join(root, file)))

images = np.array(images)

tifffile.imsave(os.path.join(dir, args.output), images)
