#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import argparse
import re
import glob
import fnmatch
import tifffile
import numpy as np


parser = argparse.ArgumentParser()
parser.add_argument('dir')
parser.add_argument("--pattern", default="*.tif*")
parser.add_argument("--output", default="combined.tiff")
args = parser.parse_args()

image_fnames = []
dir = args.dir
for root, dirs, files in os.walk(dir):
    for file in files:
        if fnmatch.fnmatch(os.path.join(root, file), args.pattern):
            image_fnames.append(os.path.join(root, file))
image_fnames.sort()
print(image_fnames)
images = [tifffile.imread(f) for f in image_fnames]

if len(images) == 0:
    raise ValueError("No matching image found.")

if images[0].ndim == 2:
    images = np.array(images)
else:
    images = np.concat(images)

tifffile.imwrite(os.path.join(dir, args.output), images)
