#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

import argparse
import os
import sys
import numpy as np
import tifffile

def main(arg):

    parser = argparse.ArgumentParser()
    parser.add_argument("file")
    parser.add_argument("--type", help="magnitude or phase",default='magnitude')
    args = parser.parse_args()

    a = np.load(args.file)
    print('Shape: {}'.format(a.shape))
    print('Dtype: {}'.format(a.dtype))
    if args.type == 'magnitude':
        tifffile.imwrite(os.path.splitext(os.path.basename(args.file))[0] + '_mag.tiff', abs(a))
    elif args.type == 'phase':
        tifffile.imwrite(os.path.splitext(os.path.basename(args.file))[0] + '_phase.tiff', np.angle(a))
    return

if __name__ == '__main__':
    main(sys.argv)