#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

import argparse
import os
import sys
import numpy as np
import tifffile

def main(arg):

    parser = argparse.ArgumentParser()
    parser.add_argument("file")
    parser.add_argument("--type", help="magnitude or phase",default='magnitude')
    args = parser.parse_args()

    a = np.load(args.file)
    if args.type == 'magnitude':
        tifffile.imwrite(os.path.splitext(os.path.basename(args.file))[0] + '_mag', abs(a), dtype='float32')
    elif args.type == 'phase':
        tifffile.imwrite(os.path.splitext(os.path.basename(args.file))[0] + '_mag', np.angle(a), dtype='float32')
    return

if __name__ == '__main__':
    main(sys.argv)