#!/usr/bin/env python
# -*- coding: utf-8 -*-

import numpy as np
import matplotlib.pyplot as plt
import tifffile

import argparse
import os


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('fname')
    args = parser.parse_args()

    fname = args.fname
    ext = os.path.splitext(fname)[-1]
    
    if ext == '.tiff':
        img = tifffile.imread(fname)
    elif ext == '.npy':
        img = np.load(fname)
    else:
        raise Exception('Unknown extension: {}'.format(ext))

    if np.iscomplexobj(img):
        fig, ax = plt.subplots(1, 2)
        ax[0].imshow(abs(img))
        ax[0].set_title('magnitude')
        ax[1].imshow(np.angle(img))
        ax[1].set_title('phase')
    else:
        fig, ax = plt.subplots(1, 1)
        ax.imshow(img)
    plt.show()
