#!/usr/bin/env python
# -*- coding: utf-8 -*-

import h5py


def print_h5_group_recursive(grp: h5py.Group | h5py.File, indent: int = 0):
    indent_string = "  " * indent
    for key in grp.keys():
        if isinstance(grp[key], h5py.Group):
            print(f"{indent_string}Group: {key}")
            print_h5_group_recursive(grp[key], indent + 1)
        else:
            if grp[key].size < 2:
                print(f"{indent_string}Dataset: {key} = {grp[key][...]}")
            else:
                print(f"{indent_string}Dataset: {key}: {grp[key]}")


def show_hdf5(f: h5py.File):
    print_h5_group_recursive(f)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("filename")
    args = parser.parse_args()
    with h5py.File(args.filename, "r") as f:
        show_hdf5(f)