#!/usr/bin/env python
# -*- coding: utf-8 -*-

import numpy as np
import matplotlib.pyplot as plt
import tifffile

import argparse
import os


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('fname')
    args = parser.parse_args()

    fname = args.fname
    ext = os.path.splitext(fname)[-1]
    
    if ext == '.tiff':
        img = tifffile.imread(fname)
    elif ext == '.npy':
        img = np.load(fname)
    else:
        raise Exception('Unknown extension: {}'.format(ext))

    if img.ndim == 2:
        img = img[None, ...]
    if np.iscomplexobj(img):
        fig, ax = plt.subplots(len(img), 2, squeeze=False)
    else:
        fig, ax = plt.subplots(len(img), 1, squeeze=False)
    for i, im in enumerate(img):
        if np.iscomplexobj(img):
            ax[i, 0].imshow(abs(im))
            ax[i, 0].set_title('magnitude')
            ax[i, 1].imshow(np.angle(im))
            ax[i, 1].set_title('phase')
        else:
            ax[i, 0].imshow(im)
    plt.show()
