#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
import matplotlib.pyplot as plt
import tifffile

import argparse
import os

import xommons.plot as xp


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("fname")
    parser.add_argument("--component", choices=["real", "imag", "mag", "phase"], default="mag")
    args = parser.parse_args()

    fname = args.fname
    ext = os.path.splitext(fname)[-1]
    
    if ext == ".tiff":
        img = tifffile.imread(fname)
    elif ext == ".npy":
        img = np.load(fname)
    else:
        raise Exception("Unknown extension: {}".format(ext))

    if img.ndim == 2:
        img = img[None, None, ...]
    if img.ndim == 3:
        img = img[None, ...]
        
    if args.component == "real":
        img = np.real(img)
    elif args.component == "imag":
        img = np.imag(img)
    elif args.component == "mag":
        img = np.abs(img)
    elif args.component == "phase":
        img = np.angle(img)
   
    fig = xp.plot_ptychi_probe(img)
    plt.show()
