#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import os

import numpy as np
import torch
import tifffile
import matplotlib.pyplot as plt
try:
    import ptychi.image_proc as ip
except ImportError:
    raise ImportError("uwnrap_phase requires Pty-Chi. Install it with `pip install ptychi`")


parser = argparse.ArgumentParser()
parser.add_argument('filename')
parser.add_argument('--show', action='store_true')
args = parser.parse_args()

arr = np.load(args.filename)
arr = torch.tensor(arr)
if arr.ndim == 2:
    arr = arr[None, ...]

res = []
for i_slice in range(arr.shape[0]):
    arr_slice = arr[i_slice, ...]
    phase = ip.unwrap_phase_2d(
        arr_slice,
        image_grad_method="fourier_differentiation",
        image_integration_method="fourier"
    )
    res.append(phase)

if args.show:
    for i_slice in range(res.shape[0]):
        plt.imshow(res[i_slice].cpu().numpy())
        plt.colorbar()
        plt.show()

res = torch.stack(res)
tifffile.imwrite(os.path.splitext(args.filename)[0] + "_unwrapped_phase.tiff", res.cpu().numpy())